CREATE TABLE [ETL].[TASKS]
(
	[ID] INT IDENTITY(1,1) PRIMARY KEY,
	[NAME] NVARCHAR(50) NOT NULL,
	[SOURCE_ID] INT REFERENCES [ETL].[DATASOURCE](ID) NOT NULL,
	[TARGET_ID] INT REFERENCES [ETL].[DATASOURCE](ID) NOT NULL,
	[DATA_QUERY] NVARCHAR(4000) NOT NULL,
	[TARGET_TABLE] NVARCHAR(50) NULL,
	[STATUS] BIT DEFAULT(0)
)
