--ADD SQL SOURCE TO ETL.DATASOURCE TABLE, RETURN INSERTED OR EXISTED ROW
CREATE PROCEDURE [ETL].[addSource]
	@SourceName nvarchar(50),
	@ConnectionString nvarchar(255)
AS
BEGIN
	IF(NOT EXISTS (SELECT * FROM ETL.DATASOURCE WHERE NAME = @SourceName))
	BEGIN
		INSERT INTO ETL.DATASOURCE(NAME, CONNECTION)
			VALUES( @SourceName, @ConnectionString);

		SELECT  @@IDENTITY AS [ID], @SourceName AS [NAME], @ConnectionString AS [CONNETION];
	END
	ELSE
	BEGIN
		SELECT [ID], [NAME], [CONNECTION] FROM ETL.DATASOURCE WHERE NAME = @SourceName;
		PRINT 'THIS SOURCE IS ALREADY EXISTS';
	END
END
